/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SymptomsRouteImport } from './routes/symptoms'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CareRouteImport } from './routes/care'
import { Route as IndexRouteImport } from './routes/index'

const SymptomsRoute = SymptomsRouteImport.update({
  id: '/symptoms',
  path: '/symptoms',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CareRoute = CareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/care': typeof CareRoute
  '/chat': typeof ChatRoute
  '/symptoms': typeof SymptomsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/care': typeof CareRoute
  '/chat': typeof ChatRoute
  '/symptoms': typeof SymptomsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/care': typeof CareRoute
  '/chat': typeof ChatRoute
  '/symptoms': typeof SymptomsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/care' | '/chat' | '/symptoms'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/care' | '/chat' | '/symptoms'
  id: '__root__' | '/' | '/care' | '/chat' | '/symptoms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareRoute: typeof CareRoute
  ChatRoute: typeof ChatRoute
  SymptomsRoute: typeof SymptomsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/symptoms': {
      id: '/symptoms'
      path: '/symptoms'
      fullPath: '/symptoms'
      preLoaderRoute: typeof SymptomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care': {
      id: '/care'
      path: '/care'
      fullPath: '/care'
      preLoaderRoute: typeof CareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareRoute: CareRoute,
  ChatRoute: ChatRoute,
  SymptomsRoute: SymptomsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
